CREATE TABLE ZipcodeAllowed (
  Id INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  Zipcode VARCHAR(16) NOT NULL UNIQUE,
  City VARCHAR(100) NOT NULL,
  State VARCHAR(50) NOT NULL,
  isSameDayEligible TINYINT(1) NOT NULL DEFAULT 0,
  TaxRate DECIMAL(6,4) NOT NULL DEFAULT 0.10,
  DateAdded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
