CREATE TABLE Devices (
  Id INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  DeviceSignature CHAR(64) NOT NULL UNIQUE,
  DeviceType VARCHAR(50) NOT NULL,
  Zipcode VARCHAR(16) NOT NULL,
  isSameDayEligible TINYINT(1) NOT NULL DEFAULT 0,
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  DateAdded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_device_sig (DeviceSignature),
  INDEX idx_zipcode (Zipcode)
);