CREATE TABLE Devices (
  Id int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  DeviceSignature LONGTEXT NOT NULL,
  DeviceType LONGTEXT NOT NULL,
  ZipCode LONGTEXT NOT NULL,
  UserAddress LONGTEXT NOT NULL,
  isActive LONGTEXT NOT NULL,
  DateAdded LONGTEXT NOT NULL
);