CREATE TABLE Themes (
  Id INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  Name VARCHAR(100) NOT NULL UNIQUE,
  StartDate DATETIME NOT NULL,
  EndDate DATETIME NOT NULL,
  DateAdded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IsActive TINYINT(1) NOT NULL DEFAULT 1,
  INDEX idx_is_active (IsActive),
  INDEX idx_start_date (StartDate),
  INDEX idx_end_date (EndDate)
);

CREATE TABLE ThemeAssets (
  Id INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ThemeId INT(11) NOT NULL,
  AssetKey VARCHAR(100) NOT NULL,
  AssetValue TEXT NOT NULL,
  DateAdded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_theme_key (ThemeId, AssetKey),
  FOREIGN KEY (ThemeId) REFERENCES Themes(Id) ON DELETE CASCADE,
  INDEX idx_theme_id (ThemeId),
  INDEX idx_asset_key (AssetKey)
);