CREATE TABLE Process (
  Id int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  UserId LONGTEXT NOT NULL,
  ProductId LONGTEXT NOT NULL,
  Quantity LONGTEXT NOT NULL,
  isStocked LONGTEXT NOT NULL,
  DateAdded LONGTEXT NOT NULL,
  TimeAdded LONGTEXT NOT NULL,
  isMissing LONGTEXT NOT NULL
);