CREATE TABLE OrderSent (
  Id INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  UserId INT(11) NOT NULL,
  ItemQuantity INT(11) NOT NULL,
  OrderRevenue DECIMAL(10,2) NOT NULL,
  FinalOrderRevenue DECIMAL(10,2) NOT NULL,
  OrderLiability DECIMAL(10,2) NOT NULL,
  HandlerId INT(11) NOT NULL DEFAULT 0,
  TipAmount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  CreditsEarned DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  isSameDay TINYINT(1) NOT NULL DEFAULT 0,
  OrderStatus VARCHAR(50) NOT NULL DEFAULT 'pending',
  DateAdded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  TimeDelivered DATETIME NULL,
  ScheduledDeliveryWindow VARCHAR(100) NULL,
  isRated TINYINT(1) NOT NULL DEFAULT 0,
  isTipped TINYINT(1) NOT NULL DEFAULT 0,
  isClosed TINYINT(1) NOT NULL DEFAULT 0,
  FOREIGN KEY (UserId) REFERENCES Users(Id),
  INDEX idx_user_id (UserId),
  INDEX idx_order_status (OrderStatus),
  INDEX idx_date_added (DateAdded)
);

CREATE TABLE OrderTracking (
  Id INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  UserId INT(11) NOT NULL,
  ProductId INT(11) NOT NULL,
  OrderId INT(11) NULL,
  ItemQuantity INT(11) NOT NULL,
  OrderRevenue DECIMAL(10,2) NOT NULL,
  OrderLiability DECIMAL(10,2) NOT NULL,
  HandlerId INT(11) NOT NULL DEFAULT 0,
  DateAdded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  isMissing TINYINT(1) NOT NULL DEFAULT 0,
  TrackingStatus VARCHAR(50) NOT NULL DEFAULT 'pending',
  TimeDelivered DATETIME NULL,
  FOREIGN KEY (UserId) REFERENCES Users(Id),
  FOREIGN KEY (ProductId) REFERENCES Products(Id),
  FOREIGN KEY (OrderId) REFERENCES OrderSent(Id),
  INDEX idx_user_id (UserId),
  INDEX idx_product_id (ProductId),
  INDEX idx_order_id (OrderId),
  INDEX idx_tracking_status (TrackingStatus)
);