CREATE TABLE OrderSent (
  Id int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  UserId LONGTEXT NOT NULL,
  ItemQuantity LONGTEXT NOT NULL,
  OrderRevenue LONGTEXT NOT NULL,
  ConstantOrderRevenue LONGTEXT NOT NULL,
  OrderLiability LONGTEXT NOT NULL,
  HandlerId LONGTEXT NOT NULL,
  OrderStatus LONGTEXT NOT NULL,
  DateAdded LONGTEXT NOT NULL,
  TimeAdded LONGTEXT NOT NULL,
  TimeDelivered LONGTEXT NOT NULL,
  isRated LONGTEXT NOT NULL,
  isTipped LONGTEXT NOT NULL,
  isSameDay LONGTEXT NOT NULL
);
