CREATE TABLE PasswordResetCodes (
  Id         INT(11)      AUTO_INCREMENT PRIMARY KEY NOT NULL,
  Email      VARCHAR(255) NOT NULL UNIQUE,
  UniqueCode CHAR(6)      NOT NULL,
  SentIn     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ExpiredAt  DATETIME     NOT NULL
);
