CREATE TABLE Products (
  Id int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  Brand LONGTEXT NOT NULL,
  Pr_Category LONGTEXT NOT NULL,
  Snd_Category LONGTEXT NOT NULL,
  Thd_Category LONGTEXT NOT NULL,
  Ext_Category LONGTEXT NOT NULL,
  Name LONGTEXT NOT NULL,
  Oz LONGTEXT NOT NULL,
  Price LONGTEXT NOT NULL,
  isOnSale LONGTEXT NOT NULL,
  SalePrice LONGTEXT NOT NULL,
  isBogo LONGTEXT NOT NULL,
  inStock LONGTEXT NOT NULL,
  Description LONGTEXT NOT NULL
);