CREATE TABLE ProductImages (
  Id INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ProductId INT(11) NOT NULL,
  ImageUrl VARCHAR(500) NOT NULL,
  DateAdded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE CASCADE,
  INDEX idx_product_id (ProductId),
  INDEX idx_date_added (DateAdded)
);